[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "solo-server"
version = "0.1.0"
description = "A library for running AI models as services"
requires-python = ">=3.8"