services:
  solo-api:
    build:
      context: .
      args:
        PYTHON_FILE: ${PYTHON_FILE:-src/predict.py}
    container_name: "solo-api"
    ports:
      - "8000:8000"
    environment:
      - PYTHON_FILE=${PYTHON_FILE:-src/predict.py}

networks:
  solo-network:
    driver: bridge
