[project]
name = "solo-server-llm"
version = "0.1.0"
description = "LLM template for Solo Server"
dependencies = [
    "litserve",
    "wget",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"