[project]
name = "solo-server-huggingface"
version = "0.1.0"
description = "Hugging Face template for Solo Server"
dependencies = [
    "litserve",
    "torch==2.3",
    "transformers",
    "streamlit",
    "requests",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"