version: '3.7'

services:
  timescale:
    image: cyberw/locust-timescale:latest
    container_name: timescale_postgres
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - timescale_postgres_data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:latest
    container_name: timescale_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - timescale
    volumes:
      - grafana_data:/var/lib/grafana

  locust:
    build:
      context: ./app/benchmark
    container_name: locust_benchmark
    command: >
      locust
      --headless
      --users 10
      --spawn-rate 2
      --run-time 1m
      --host http://solo-api:8000
      --timescale
    depends_on:
      - solo-api
    environment:
      LOCUST_HOST: http://solo-api:8000
    networks:
      - solo-network

  solo-api:
    build:
      context: .
      args:
        PYTHON_FILE: ${PYTHON_FILE:-solo_server/templates/basic.py}
    container_name: "solo-api"
    environment:
      - PYTHON_FILE=${PYTHON_FILE:-solo_server/templates/basic.py}
      - MODEL_URL=${MODEL_URL:-your_model_url_here}
      - MODEL_FILENAME=${MODEL_FILENAME:-your_model_filename_here}

volumes:
  timescale_postgres_data:
  grafana_data:

networks:
  solo-network:
    driver: bridge
