[project]
name = "solo-server-vision"
version = "0.1.0"
description = "Vision template for Solo Server"
dependencies = [
    "litserve",
    "torch==2.3",
    "transformers",
    "pillow",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"