version: '3.7'

services:
  timescale:
    image: timescale/timescaledb:latest-pg14
    container_name: timescale_postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: locust
    ports:
      - "5433:5432"
    volumes:
      - timescale_postgres_data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:latest
    container_name: timescale_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - timescale
    volumes:
      - grafana_data:/var/lib/grafana

  locust:
    image: locustio/locust:latest
    container_name: locust_benchmark
    volumes:
      - ./locustfile.py:/home/locust/locustfile.py
    command: >
      -f /home/locust/locustfile.py
      --host http://host.docker.internal:8000
      --users 10
      --spawn-rate 2
      --run-time 1m
    ports:
      - "8089:8089"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  timescale_postgres_data:
  grafana_data:

networks:
  solo-network:
    driver: bridge